export const duroos = [
    {
        categorytitle: "Dawrah Ilmiyyah (Mukhtasar)",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains Taweel lectures on Raf'ul Malam, Tadween As Sunnah, Al-Arba'oona An-Nawawi",
        categoryimage: "/images/categories/6.png",
        subcategories: [
            {
                title: "Raf'ul Malam",
                description: "",
                image: "/images/20.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hn__yls0YW0POpbt-Hp4APZ",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1-lsbdF9fKIoVkT5l2HMBv_0jsD8VoapL",
                listenlink: "https://archive.org/embed/raf-al-malam-an-al-aimmat-al-alam-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Tadween As sunnah",
                description: "",
                image: "/images/30.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hn_EzJv5bmRNWRmC2eJSTvO",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1Fx6WbJG3y2mmkrSuKSWXJZz3FBwd80mf",
                listenlink: "https://archive.org/embed/tadween-as-sunnah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Al-Arba'oona An-Nawawi",
                description: "",
                image: "/images/6.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1-lsbdF9fKIoVkT5l2HMBv_0jsD8VoapL",
                listenlink: "https://archive.org/embed/40-ahaadeth-imaam-an-nawawi--zafarulhasan-madani&playlist=1&list_height=550",
            },
        ]
    },
    {
        categorytitle: "Dawrah Ilmiyyah (Taweel)",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/5.png",
        subcategories: [
            {
                title: "Al Arba'oona Nawawiyyah",
                description: "",
                image: "/images/6.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/1/folders/1azueqYmaJAcOntjy9hxks029gnVIGyky",
                listenlink: "",
            },
            {
                title: "Sharh As-Sunnah",
                description: "",
                image: "/images/26.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "",
                listenlink: "",
            },
            {
                title: "Bulugh al-Maram",
                description: "",
                image: "/images/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hltNDJamXol6XA04VzJKIng",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1dt9ClL2vhPPiz9UtfzwRyWNvFpHOj1dw",
                listenlink: "",
            },
            {
                title: "Usool al-Thalatha",
                description: "",
                image: "/images/24.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlVgAZOuDvaowaj9uPKoYWL",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1b_iM6DBbrbbMP7p7-KzuRVeH-wZDPwts",
                listenlink: "https://archive.org/embed/3-fundamental-principles-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Shamail al-Muhammadiyah",
                description: "",
                image: "/images/28.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hk_6GGFntSM-IwahZs_cJb6",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1SNvR6J81FrBQjwmWofW5U3PLeCQKEIvN",
                listenlink: "https://archive.org/embed/sharh-shamail-muhammadiyah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Riyad us-saliheen",
                description: "",
                image: "/images/12.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hm8ojp4-oHK9GMrHKjcIDyB",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1MxPz38wGwGKZHumOMAU6ZaJemvDG9PTn",
                listenlink: "",
            },
        ]
    },
    {
        categorytitle: "Tafseerul Quran",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/2.png",
        subcategories: [
            {
                title: "Juz 28",
                description: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
                image: "/images/tafseer/1.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hkqUMWwsIRn8yfhBT_pTJeu",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/2/folders/1QDYR6uAfIt5nvBdnxzkJC670Aayr9t8K",
                listenlink: "https://archive.org/details/tafseer-juz-28-zafarulhasan-madani",
            },
            {
                title: "Juz 27",
                description: "The Sheikh explains that this Surah is considered Makki, meaning it was revealed during the Prophet Muhammad's time in Mecca. The discussion focuses on the oaths sworn by Allah in these verses, interpreting them as proofs of the truth of the resurrection and the Day of Judgment, and refuting the doubts and mockery of those who deny these realities. The commentary highlights various signs of Allah's power in creation, such as the winds, rain-bearing clouds, and ships at sea, as well as the qualities of the righteous (Muttaqin) who will be rewarded in Paradise.",
                image: "/images/tafseer/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hkjhxQIcMm7YRBEJnWzpNCg",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1k-O0tHKvkC68OJ7E_UmPsKwT42-arFT-",
                listenlink: "https://archive.org/details/tafseer-juz-27-zafarulhasan-madani",
            },
            {
                title: "Surah Al-Fathiha",
                description: "The Sheikh focuses on the profound meaning of the Arabic word 'Rabb' (often translated as 'Lord' or 'Cherisher') within the context of the Quran, particularly in Surah Al-Fatiha and its significance in establishing God's absolute oneness and right to worship. The speaker emphasizes that 'Rabb' signifies the One who nurtures, sustains, and fulfills the needs of all creation in every situation, highlighting this attribute as the basis for deserving worship. The repeated use of the word 'Rabb' in the Quran, particularly in confronting disbelievers like Pharaoh and Nimrod, demonstrates its power in arguing for the exclusive sovereignty and right to worship of Allah. Ultimately, the source argues that recognizing Allah as the sole 'Rabb' who creates and provides is essential to understanding and practicing true monotheism.",
                image: "/images/tafseer/3.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hmrbtAWVVqCe3I_ckqaZ80L",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1nkn6uvAhcVPAeLqURfsUN0mw-Vg4PhrQ",
                listenlink: "https://archive.org/embed/tafseer-surah-al-fatihah-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Juz Tabarak",
                description: "Sheikh emphasizes the importance and necessity of understanding the Quran through translation and commentary (Tafseer). The speaker explains that the Quran serves as a source of guidance, healing for inner ailments, and a reminder through stories and examples, illustrating this with the story of the Bani Israel being turned into monkeys. He highlights the efforts of scholars in the Indian subcontinent over centuries to make the Quran accessible through translations in Persian and Urdu and comprehensive commentaries, seeing these efforts as crucial for the reform and enlightenment of the Muslim community after periods of deviation.",
                image: "/images/tafseer/4.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlVgAZOuDvaowaj9uPKoYWL",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1b_iM6DBbrbbMP7p7-KzuRVeH-wZDPwts",
                listenlink: "",
            },
            {
                title: "Kuch Lamhaat quran ki ayaton ke sath",
                description: "",
                image: "/images/tafseer/5.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hkqk4C-GaDhjeeJ6EOMrKQn",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1_DVbZm2rItVlUumvpvsMN_grNisfZvgY",
                listenlink: "",
            },
            {
                title: "Surah Al-Baqarah",
                description: "",
                image: "/images/tafseer/6.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hnUIJCsllm7pOS69SFVYp6s",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1_DVbZm2rItVlUumvpvsMN_grNisfZvgY",
                listenlink: "",
            },
            {
                title: "Surah Al-An'aam",
                description: "",
                image: "/images/tafseer/7.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hnUIJCsllm7pOS69SFVYp6s",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1wtOGs_z1LXPLo4mSQ_-efg_-v5SJTQ9q",
                listenlink: "https://archive.org/embed/tafseer-surah-al-anaam-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Surah Al-A'raf",
                description: "",
                image: "/images/tafseer/8.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlONJRQuaZVQbEo4-GXi6P_",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1G8aGJm0FBAJTwDbTfaVIVhqwXbaX6jDa",
                listenlink: "https://archive.org/embed/tafseer-surah-al-aaraaf-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Surah Ibrahim",
                description: "",
                image: "/images/tafseer/9.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hnh7frFqrdGfN4jpYBlVpwR",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1scvzQY1-AMhyCHtEHt-pWpeh7VLlHN2u",
                listenlink: "https://archive.org/embed/tafseer-surah-ibrahim-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Surah Al-Hijr",
                description: "",
                image: "/images/tafseer/10.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlyzrdduZWffLfCD6Hn-r3N",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1c2HpapauLcvqa6QTRZaBLe1ab4CAsA_d",
                listenlink: "https://archive.org/embed/tafseer-surah-al-hijr-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Surah Al-Ahzab",
                description: "",
                image: "/images/tafseer/11.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hnOkXpPxX13u9XeTMuIuOeF",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1TvmsuTMhQOYuvL8vqdChlFLqlo9GUupJ",
                listenlink: "https://archive.org/embed/tafseer-surah-al-ahzab-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Surah Saba",
                description: "",
                image: "/images/tafseer/12.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hnOS3IxjbBwIVxR5v_hhU7X",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1EbMJ6STpDm-uXSXKYT6-HR96GxCq6eeK",
                listenlink: "https://archive.org/embed/tafseer-surah-saba-zafarulhasan-madani&playlist=1&list_height=400",
            },
            {
                title: "Surah Al-Hujurat",
                description: "",
                image: "/images/tafseer/13.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hnB5SYT-dP55VpAM4jFuwtW",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1pO-2yC0C4PJQ3IJKWYKzuM5W9Zl-DQ5h",
                listenlink: "https://archive.org/embed/tafsir-surah-al-hujraat-zafarulhasan-madani&playlist=1&list_height=400",
            },
        ]
    },
    {
        categorytitle: "Jummu'ah Khutbah",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/1.png",
        subcategories: [
            {
                title: "Al Arba'oona Nawawiyyah",
                description: "",
                image: "/images/6.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/1/folders/1azueqYmaJAcOntjy9hxks029gnVIGyky",
                listenlink: "",
            },
            {
                title: "Sharh As-Sunnah",
                description: "",
                image: "/images/26.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "",
                listenlink: "",
            },
            {
                title: "Bulugh al-Maram",
                description: "",
                image: "/images/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hltNDJamXol6XA04VzJKIng",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1dt9ClL2vhPPiz9UtfzwRyWNvFpHOj1dw",
                listenlink: "",
            },
            {
                title: "Usool al-Thalatha",
                description: "",
                image: "/images/24.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlVgAZOuDvaowaj9uPKoYWL",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1b_iM6DBbrbbMP7p7-KzuRVeH-wZDPwts",
                listenlink: "https://archive.org/embed/3-fundamental-principles-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Shamail al-Muhammadiyah",
                description: "",
                image: "/images/28.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hk_6GGFntSM-IwahZs_cJb6",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1SNvR6J81FrBQjwmWofW5U3PLeCQKEIvN",
                listenlink: "https://archive.org/embed/sharh-shamail-muhammadiyah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Riyad us-saliheen",
                description: "",
                image: "/images/12.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hm8ojp4-oHK9GMrHKjcIDyB",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1MxPz38wGwGKZHumOMAU6ZaJemvDG9PTn",
                listenlink: "",
            },
        ]
    },
    {
        categorytitle: "Arkan Al Islam",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/3.png",
        subcategories: [
            {
                title: "Al Arba'oona Nawawiyyah",
                description: "",
                image: "/images/6.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/1/folders/1azueqYmaJAcOntjy9hxks029gnVIGyky",
                listenlink: "",
            },
            {
                title: "Sharh As-Sunnah",
                description: "",
                image: "/images/26.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "",
                listenlink: "",
            },
            {
                title: "Bulugh al-Maram",
                description: "",
                image: "/images/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hltNDJamXol6XA04VzJKIng",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1dt9ClL2vhPPiz9UtfzwRyWNvFpHOj1dw",
                listenlink: "",
            },
            {
                title: "Usool al-Thalatha",
                description: "",
                image: "/images/24.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlVgAZOuDvaowaj9uPKoYWL",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1b_iM6DBbrbbMP7p7-KzuRVeH-wZDPwts",
                listenlink: "https://archive.org/embed/3-fundamental-principles-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Shamail al-Muhammadiyah",
                description: "",
                image: "/images/28.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hk_6GGFntSM-IwahZs_cJb6",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1SNvR6J81FrBQjwmWofW5U3PLeCQKEIvN",
                listenlink: "https://archive.org/embed/sharh-shamail-muhammadiyah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Riyad us-saliheen",
                description: "",
                image: "/images/12.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hm8ojp4-oHK9GMrHKjcIDyB",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1MxPz38wGwGKZHumOMAU6ZaJemvDG9PTn",
                listenlink: "",
            },
        ]
    },
    {
        categorytitle: "Mausamiat",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/4.png",
        subcategories: [
            {
                title: "Al Arba'oona Nawawiyyah",
                description: "",
                image: "/images/6.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/1/folders/1azueqYmaJAcOntjy9hxks029gnVIGyky",
                listenlink: "",
            },
            {
                title: "Sharh As-Sunnah",
                description: "",
                image: "/images/26.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "",
                listenlink: "",
            },
            {
                title: "Bulugh al-Maram",
                description: "",
                image: "/images/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hltNDJamXol6XA04VzJKIng",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1dt9ClL2vhPPiz9UtfzwRyWNvFpHOj1dw",
                listenlink: "",
            },
            {
                title: "Usool al-Thalatha",
                description: "",
                image: "/images/24.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlVgAZOuDvaowaj9uPKoYWL",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1b_iM6DBbrbbMP7p7-KzuRVeH-wZDPwts",
                listenlink: "https://archive.org/embed/3-fundamental-principles-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Shamail al-Muhammadiyah",
                description: "",
                image: "/images/28.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hk_6GGFntSM-IwahZs_cJb6",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1SNvR6J81FrBQjwmWofW5U3PLeCQKEIvN",
                listenlink: "https://archive.org/embed/sharh-shamail-muhammadiyah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Riyad us-saliheen",
                description: "",
                image: "/images/12.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hm8ojp4-oHK9GMrHKjcIDyB",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1MxPz38wGwGKZHumOMAU6ZaJemvDG9PTn",
                listenlink: "",
            },
        ]
    },
    {
        categorytitle: "Aam Duroos",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/7.png",
        subcategories: [
            {
                title: "Isteqamat",
                description: "",
                image: "/images/aamduroos/1.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hmd_vS2BTCk6n43tGG5IaIr",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/1LVbol0FZAEe8Y2efbnV9jNJLbQN95fkT",
                listenlink: "https://archive.org/embed/istiqamah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Dil ke Amaal",
                description: "",
                image: "/images/aamduroos/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hk9I9izzkKXm2DO05-5-YsY",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/1/folders/1rgVlY1adu7MNnOIdl2B4fk7wCiOup-qC",
                listenlink: "",
            },
        ]
    },
    {
        categorytitle: "Sister's section",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/8.png",
        subcategories: [
            {
                title: "Nisa",
                description: "",
                image: "/images/sister/nisa.png",
                YTplaylistlink: "https://www.youtube.com/watch?v=VVTVdB6Rp7Q&list=PLmZP1KIsC-hnxbVOity71qHq_YqO6Ui5G",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/folders/15fDSK6rNln1xfP5hPi13jsP4vFsc1LwU",
                listenlink: "",
            },
        ]
    },
    {
        categorytitle: "Tareeq Ahlul Hadith",
        categorydescrption: "The series of lessons undertook by Sheikh Zafarul Hasan Madani. This category contains brief lectures on the topic Al Arba'oona Nawawiyyah, Sharh As-Sunnah, Bulugh al-Maram, Usool al-Thalatha, Shamail al-Muhammadiyah, Riyad us-saliheen",
        categoryimage: "/images/categories/9.png",
        subcategories: [
            {
                title: "Al Arba'oona Nawawiyyah",
                description: "",
                image: "/images/6.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/1/folders/1azueqYmaJAcOntjy9hxks029gnVIGyky",
                listenlink: "",
            },
            {
                title: "Sharh As-Sunnah",
                description: "",
                image: "/images/26.png",
                YTplaylistlink: "",
                introYTlink:"",
                drivelink: "",
                listenlink: "",
            },
            {
                title: "Bulugh al-Maram",
                description: "",
                image: "/images/2.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hltNDJamXol6XA04VzJKIng",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1dt9ClL2vhPPiz9UtfzwRyWNvFpHOj1dw",
                listenlink: "",
            },
            {
                title: "Usool al-Thalatha",
                description: "",
                image: "/images/24.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hlVgAZOuDvaowaj9uPKoYWL",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1b_iM6DBbrbbMP7p7-KzuRVeH-wZDPwts",
                listenlink: "https://archive.org/embed/3-fundamental-principles-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Shamail al-Muhammadiyah",
                description: "",
                image: "/images/28.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hk_6GGFntSM-IwahZs_cJb6",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1SNvR6J81FrBQjwmWofW5U3PLeCQKEIvN",
                listenlink: "https://archive.org/embed/sharh-shamail-muhammadiyah-zafarulhasan-madani&playlist=1&list_height=550",
            },
            {
                title: "Riyad us-saliheen",
                description: "",
                image: "/images/12.png",
                YTplaylistlink: "https://www.youtube.com/playlist?list=PLmZP1KIsC-hm8ojp4-oHK9GMrHKjcIDyB",
                introYTlink:"",
                drivelink: "https://drive.google.com/drive/u/0/folders/1MxPz38wGwGKZHumOMAU6ZaJemvDG9PTn",
                listenlink: "",
            },
        ]
    },
]

export default duroos;